1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.


In [9]:
import numpy as np
import pandas as pd
import random

In [10]:
arr = np.random.randint(1, 21, size=(5,5))
print(arr)

[[19 12  3 11  5]
 [ 1 11  9  1 14]
 [ 8 10 15 18  9]
 [14  6  7  4 10]
 [11 15  4  7 11]]


In [11]:
arr[:, 2] =  1
arr

array([[19, 12,  1, 11,  5],
       [ 1, 11,  1,  1, 14],
       [ 8, 10,  1, 18,  9],
       [14,  6,  1,  4, 10],
       [11, 15,  1,  7, 11]])

2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [12]:
arr2 = np.random.randint(1, 16, size=(4,4))
arr2

array([[ 7,  6, 10,  3],
       [ 1, 15,  8,  4],
       [15, 11, 15,  1],
       [ 1,  6,  8,  2]])

In [13]:
np.fill_diagonal(arr2, 0,wrap=True)
arr2

array([[ 0,  6, 10,  3],
       [ 1,  0,  8,  4],
       [15, 11,  0,  1],
       [ 1,  6,  8,  0]])

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.


In [14]:
arr3 = np.random.randint(1, 32, size=(6,6))
arr3

array([[ 4, 31, 26, 27, 29, 18],
       [27, 13, 19,  9, 16, 10],
       [26, 16,  6, 11, 31, 23],
       [ 4,  3,  4, 29,  9, 16],
       [ 4, 27, 25, 12,  9,  6],
       [20,  8,  5, 10,  5, 14]])

In [28]:
arr4 = arr3[0:3]
arr4

array([[ 4, 31, 26, 27, 29, 18],
       [27, 13, 19,  9, 16, 10],
       [26, 16,  6, 11, 31, 23]])

2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.


In [29]:
arr5=np.random.randint(1, 30, size=(5,5))
arr5

array([[18, 23, 11, 14, 18],
       [28, 23, 20, 24, 19],
       [ 4, 19, 28,  8, 26],
       [26,  7, 15, 21,  3],
       [27,  7, 25, 11, 10]])

In [ ]:
border_value = False

# the value of dim starts from 0 and then goes to 1
# so in the first iteration it attacks the first dimension
# and in the second iteration it attacks the second dimension

for dim in range(arr5.ndim):
    array_moved = np.moveaxis(arr5, dim, 0)
    array_moved[0] = border_value
    array_moved[-1] = border_value

print(arr5)

[[ 0  0  0  0  0]
 [ 0 23 20 24  0]
 [ 0 19 28  8  0]
 [ 0  7 15 21  0]
 [ 0  0  0  0  0]]


1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [33]:
array=np.random.randint(1, 20, size=(5,5))
array

array([[13, 16, 11, 15,  7],
       [ 3, 17,  9, 13, 18],
       [12, 10, 14, 11, 16],
       [ 9, 16, 10,  2, 15],
       [ 1, 10,  4, 17, 13]])

In [34]:
mean_array = np.mean(array)
mean_array

11.28

In [36]:
median_array = np.median(array)
median_array

12.0

In [37]:
standard_deviation_array = np.std(array)
standard_deviation_array

4.770911862526911

In [38]:
variance_array = np.var(array)
variance_array

22.761599999999998

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).


In [39]:
array=np.random.randint(1,9,size=(3,3))
print(array)

[[8 5 7]
 [6 7 2]
 [1 1 7]]


In [40]:
array.reshape(1,9)

array([[8, 5, 7, 6, 7, 2, 1, 1, 7]])

In [41]:
array.reshape(9,1)

array([[8],
       [5],
       [7],
       [6],
       [7],
       [2],
       [1],
       [1],
       [7]])